version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: harry
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb+srv://harshitsingh50621:6hb0YP05cMwpOPFf@cluster0.axdym9f.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

volumes:
  mongo-data:
